title = "Nikolaj Sarry Blog"
author = "Nikolaj Sarry"
copyright = "2024 - {{ YEAR }}"
description = "Nikolaj's Sarry Loft for notes, thoughts and memos about IT, project management and many other things"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
#contactFormReCaptcha = "your-site-key-here"
# Google Fonts
#googleFonts = ["Indie+Flower", "Roboto:ital,wght@0,100;0,400;0,700;1,400"]
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2/1/2006"
indexDateFormat = "2/1/2006"
listDateFormat = "2/1/2006"
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"
# relatedPosts = true
# numberOfRelatedPosts = 3


reversepagetitle = true # When set to 'true', the Window Title will be reversed to 'Title | Author' instead of the default 'Author | Title'

# hidesidebar = true

[giscus]
repo="Straven/nikolaj-sarry-blog"
repo-id="R_kgDONNc5tA"
category="Blog comments"
category-id="DIC_kwDONNc5tM4CkKUY"
mapping="pathname"
strict="0"
reactions-enabled="1"
emit-metadata="0"
input-position="bottom"
#theme="dark"
#lang="en"
loading="lazy"
crossorigin="anonymous"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

[plausibleAnalytics]
# domain = "example.com"
# serverURL = "https://analytics.example.com"

[umami]
# serverURL = "example.com"
# id = "94db1cb1-74f4-4a40-ad6c-962362670409"
# trackerScriptName = "mycustomscriptname.js"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fa-brands' when brand icons, use 'fas' when standard solid icons.
[[socialIcons]]
icon = "fa-brands fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/nikolajsarry/"

#[[socialIcons]]
#icon = "fa-brands fa-github"
#title = "GitHub"
#url = "https://github.com/lxndrblz/anatole/"

[[socialIcons]]
icon = "fa-brands fa-instagram"
title = "instagram"
url = "https://www.instagram.com/nikolaj_sarry/"

[[socialIcons]]
icon = "fa-brands fa-facebook"
title = "facebook"
url = "https://www.facebook.com/mikolaj.sarry"

[[socialIcons]]
icon = "fa-brands fa-twitter"
title = "X"
url = "https://x.com/MykolaSarry"

#[[socialIcons]]
#icon = "fa-solid fa-envelope"
#title = "e-mail"
#url = "mailto:mail@example.com"

[mermaid]
# enable = true
